### ISSUE TITLE
Cache stampede protection

### ISSUE THREAD

**Issue by samdark** [yiisoft/cache#42]
See https://en.wikipedia.org/wiki/Cache_stampede

**Comment by SilverFire** [comment]
Can be implemented as an addition to getOrSet, using Mutex

**Comment by armpogart** [comment]
What about having it `on` by default and introducing it in `Yiisoft\Cache\Cache` class (documenting that using it instead of adapter directly will give also that advantage) on all getters (not only `getOrSet`) . We can have a configuration to disable it, but Yii was always about recommending and having the good defaults and protection built-in.
I would also like to see [probabilistic early expiration](https://en.wikipedia.org/wiki/Cache_stampede#Probabilistic_early_expiration) algorithm implementation there which will be `off` by default.

I would like to work on PR for this feature if nobody started any work already. What do you think about my proposal above?

@SilverFire By Mutex do you mean [flock](https://www.php.net/manual/en/function.flock.php) in case of PHP?

I also think that locking here can be defined by interface so that other implementation would be possible as something like [flock](https://www.php.net/manual/en/function.flock.php) would guarantee only per-host locking and implementation using APC or memcached (and similar things) can be used for multi-host environment.

**Comment by SilverFire** [comment]
> @SilverFire By Mutex do you mean flock in case of PHP?

I thought about https://github.com/yiisoft/mutex
The driver implementation can by either `flock`, or Redis or SQL

> I would also like to see [probabilistic early expiration](https://en.wikipedia.org/wiki/Cache_stampede#Probabilistic_early_expiration) algorithm implementation there which will be `off` by default.

In Symfony, it is `on` by default: https://symfony.com/doc/current/components/cache.html#cache-contracts
Probabilistic early expiration is much better than locking, it should be much better than locking.
